// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1_uLN9v2sMpXJAJyRjEV0-eUHtoe8nY',
    appId: '1:1031356515191:web:a0695cef282af7f8e8d772',
    messagingSenderId: '1031356515191',
    projectId: 'romlerk',
    authDomain: 'romlerk.firebaseapp.com',
    storageBucket: 'romlerk.firebasestorage.app',
    measurementId: 'G-91S8T0EYVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdv6iK5C5p1Vw9TEirz1OmLIrrRX3owqc',
    appId: '1:1031356515191:android:2c255f4bffdc193ee8d772',
    messagingSenderId: '1031356515191',
    projectId: 'romlerk',
    storageBucket: 'romlerk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZYPndj8fSVvd4smRMW85lQzToes_v-ak',
    appId: '1:1031356515191:ios:cac69a295ba6267be8d772',
    messagingSenderId: '1031356515191',
    projectId: 'romlerk',
    storageBucket: 'romlerk.firebasestorage.app',
    iosBundleId: 'com.example.romlerk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZYPndj8fSVvd4smRMW85lQzToes_v-ak',
    appId: '1:1031356515191:ios:cac69a295ba6267be8d772',
    messagingSenderId: '1031356515191',
    projectId: 'romlerk',
    storageBucket: 'romlerk.firebasestorage.app',
    iosBundleId: 'com.example.romlerk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh1_uLN9v2sMpXJAJyRjEV0-eUHtoe8nY',
    appId: '1:1031356515191:web:63e9889eb41ad3d4e8d772',
    messagingSenderId: '1031356515191',
    projectId: 'romlerk',
    authDomain: 'romlerk.firebaseapp.com',
    storageBucket: 'romlerk.firebasestorage.app',
    measurementId: 'G-CNHE9V3BT5',
  );
}
